
name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/my-api || git clone https://github.com/afelallaric/my-api.git ~/my-api && cd ~/my-api
          git pull origin main
          docker build -t my-api:latest .
          docker stop my-api || true
          docker rm my-api || true
          docker run -d --name my-api -p 80:8000 my-api:latest
